
#
# This makefile was generated with the following command:
# /home/nikdel/g-omnet5/omnetpp-5.7/bin/opp_runall ./ErgodicityTest -u Cmdenv -f ../simulations/PretioWithLB/omnetpp.ini -c Scenario1-Type1-Short-Sessions
#

SIMULATIONCMD = ./ErgodicityTest -u Cmdenv -f ../simulations/PretioWithLB/omnetpp.ini -c Scenario1-Type1-Short-Sessions -s --cmdenv-redirect-output=true
TARGETS =  run0

.PHONY: $(TARGETS)

all: $(TARGETS)
	@echo All runs completed.

run0:
	$(SIMULATIONCMD) -r 0


